baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'SuperWoman'
theme = 'roxo-hugo'

[params.csp]
  childsrc = ["'self'", "https://amret.shinyapps.io/BudgetTool/", "https://daveywavey.shinyapps.io/Supercalculatorfinal/"]
  fontsrc = ["'self'", "https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,600,700|Montserrat:300,400,500,600,700&display=swap"]
  scriptsrc = ["'self'", "'unsafe-inline'"]

#site menu
[menu]
    #Navbar Menus
    [[menu.nav]]
        identifier = 'home'
        name = 'Home'
        url = ''
        weight = 1
    [[menu.nav]]
        identifier = 'super-calc'
        name = 'Superannuation Calculator'
        url = 'superannuation-calculator'
        weight = 2
    [[menu.nav]]
        identifier = 'budget'
        name = 'Budgeting'
        url = 'budget'
        weight = 3
    [[menu.nav]]
        identifier = 'more-info'
        name = 'More Information'
        url = 'more-info'
        weight = 4
    [[menu.nav]]
        identifier = 'resources'
        name = 'Resources'
        url = 'resources'
        weight = 2
        parent = 'more-info'
    [[menu.nav]]
        identifier = 'lifestyles'
        name = 'Retirement Lifestyles'
        url = 'retirement-lifestyles'
        weight = 1
        parent = 'more-info'